### ISSUE TITLE
[Bug]Crescent Hammer and AE2 items

### ISSUE THREAD

**Issue by devryb** [TheFantasyCraft/Forge-Permittor#7]
Using a crescent hammer I am able to remove AE2 terminals and cable from a claim even though it gives an error stating that I don't have access to use the item.

**Comment by thomas15v** [comment]
Aha, this is a famous issue. And I am afraid that I don't know an easy fix for this. I am guessing that the crescent hammer gets blocked on other items? Well the reason why it doesn't block, is because the AE2 terminals are multi-blocks. And when people interact with the multi-block's, they don't interact with the multi block instance but with the block in the block. Somehow that causes cauldron to not give off an event. 

Can you please confirm that your using the latest version of forge-permittor. Because this issue sounds similar to this #5.

**Comment by devryb** [comment]
Apologies for delay in response thats correct I was testing with Build 38 and GP 9.1

**Comment by thomas15v** [comment]
Ah oke. Friday I have my last exam. I will look for it than :smile:. Could you give me the name of the modpack you are using?

**Comment by devryb** [comment]
These tests were done with Resonant Rise Mainline which you can get from the ATLauncher.
When you install the pack make sure you click the checkbox labeled as Mainline in the optional mods that will preselect all the mods we are using.

**Comment by thomas15v** [comment]
Not fixable unless you want all items to be dropped on denied. I made some ASM patches to solve this bug: https://github.com/TheDeviantNetwork/DeviantFix. Just ask your server dev to prepare these :smile:.
